services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: amigoscode
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"

  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

#  loki:
#    image: grafana/loki:2.2.1
#    container_name: loki-service
#    volumes:
#      - /Users/Adam/Documents/Projekty/microservices/amigo:/etc/loki/
#    ports:
#      - "3100:3100"
#    command: -config.file=/etc/loki/loki.yml
#    networks:
#      - loki
#
#  promtail:
#      image: grafana/promtail:2.2.1
#      container_name: promtail-service
#      volumes:
#        - /Users/Adam/Documents/Projekty/microservices/amigo/eureka-server/logs:/var/log
#        - /Users/Adam/Documents/Projekty/microservices/amigo:/etc/promtail/
#      command: -config.file=/etc/promtail/promtail.yml
#      networks:
#        - loki
#
#  grafana:
#      image: grafana/grafana:latest
#      container_name: grafana-service
#      ports:
#        - "3000:3000"
#      networks:
#        - loki

networks:
  loki:
    driver: bridge
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin: