apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications
  labels:
    app: notifications
spec:
  replicas: 1
  template:
    metadata:
      name: notifications
      labels:
        app: notifications
    spec:
      containers:
        - name: notifications
          image: adamtomys/notifications:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kube
            - name: SPRING_DATASOURCE_USERNAME
              value: linpostgres
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://lin-16745-5592-pgsql-primary.servers.linodedb.net:5432/notifications
            - name: SPRING_DATASOURCE_PASSWORD
              value: W7vIdtVP8zGS_Uqh
      restartPolicy: Always
  selector:
    matchLabels:
      app: notifications
